/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import DAO.ConnectSQL;
import DAO.NhanVienDAO;
import DTO.NhanVien;
import SERVICE.NhanVienSERVICE;
import java.awt.Image;
import java.awt.Rectangle;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Arrays;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class CaiDatLaiMK extends javax.swing.JFrame {

    /**
     * Creates new form CaiDatLaiMK
     */
    private ConnectSQL connectSQL;
    public Connection conn = ConnectSQL.getConnection();
    public PreparedStatement ps = null;
    public ResultSet rs = null;
    
    
        NhanVien nhanVien;
        NhanVienDAO nhanVienDAO;
        NhanVienSERVICE nhanVienSERVICE = new NhanVienSERVICE();
        DefaultTableModel modelNhanVien;
        
    
    public CaiDatLaiMK() {

//        tfMaNV.setEnabled(true);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfDiaChi = new javax.swing.JTextField();
        btnCapNhat = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnMinimize4 = new javax.swing.JLabel();
        lbThoat5 = new javax.swing.JLabel();
        tfMKCu = new javax.swing.JTextField();
        btnAnNLMK = new javax.swing.JLabel();
        btnHienNLMK = new javax.swing.JLabel();
        tfMatKhau = new javax.swing.JPasswordField();
        tfMaNV = new javax.swing.JTextField();
        tfNgaySinh = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        tfTenNV = new javax.swing.JTextField();
        tfsoDT = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        lbImageNV = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        tfTenDangNhap = new javax.swing.JTextField();
        tfLinkNV = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("ID:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 30));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 102));
        jLabel4.setText("Password:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 102, 29));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 102));
        jLabel2.setText("Birthday:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 102, 29));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 102, 102));
        jLabel5.setText("Address:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 102, 29));

        tfDiaChi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDiaChiActionPerformed(evt);
            }
        });
        jPanel1.add(tfDiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 870, 40));

        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(0, 102, 102));
        btnCapNhat.setText("Update");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        jPanel1.add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 540, 113, 44));

        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThoat.setForeground(new java.awt.Color(0, 102, 102));
        btnThoat.setText("Cancel");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel1.add(btnThoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 540, 113, 44));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Update profile");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, 310, 60));

        btnMinimize4.setBackground(new java.awt.Color(49, 139, 130));
        btnMinimize4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/subtract_18px.png"))); // NOI18N
        btnMinimize4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimize4MouseClicked(evt);
            }
        });
        jPanel1.add(btnMinimize4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, -1, 33));

        lbThoat5.setBackground(new java.awt.Color(49, 139, 130));
        lbThoat5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Close_18px.png"))); // NOI18N
        lbThoat5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThoat5MouseClicked(evt);
            }
        });
        jPanel1.add(lbThoat5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 10, 30, 40));

        tfMKCu.setBackground(new java.awt.Color(250, 250, 250));
        tfMKCu.setForeground(new java.awt.Color(250, 250, 250));
        tfMKCu.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel1.add(tfMKCu, new org.netbeans.lib.awtextra.AbsoluteConstraints(8, 8, 56, 17));

        btnAnNLMK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAnNLMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/eye_16px.png"))); // NOI18N
        btnAnNLMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAnNLMKMouseClicked(evt);
            }
        });
        jPanel1.add(btnAnNLMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 30, 30));

        btnHienNLMK.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnHienNLMK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/blind_16px.png"))); // NOI18N
        btnHienNLMK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHienNLMKMouseClicked(evt);
            }
        });
        jPanel1.add(btnHienNLMK, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 30, 30));

        tfMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMatKhauActionPerformed(evt);
            }
        });
        jPanel1.add(tfMatKhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, 300, 40));

        tfMaNV.setEnabled(false);
        tfMaNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMaNVActionPerformed(evt);
            }
        });
        jPanel1.add(tfMaNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, 100, 40));

        tfNgaySinh.setDateFormatString("yyyy-MM-dd");
        jPanel1.add(tfNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 300, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 102));
        jLabel7.setText("Fullname:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 102, 29));

        tfTenNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenNVActionPerformed(evt);
            }
        });
        jPanel1.add(tfTenNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 260, 300, 40));

        tfsoDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfsoDTActionPerformed(evt);
            }
        });
        jPanel1.add(tfsoDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 300, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Phone:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 102, 29));

        lbImageNV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbImageNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/no-image209X214.png"))); // NOI18N
        lbImageNV.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lbImageNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbImageNVMouseClicked(evt);
            }
        });
        jPanel1.add(lbImageNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, 370, 280));

        btnUpload.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btnUpload.setForeground(new java.awt.Color(49, 139, 130));
        btnUpload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/openfolder_26px.png"))); // NOI18N
        btnUpload.setText("Mở hình");
        btnUpload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUploadMouseClicked(evt);
            }
        });
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 140, -1, -1));

        tfTenDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTenDangNhapActionPerformed(evt);
            }
        });
        jPanel1.add(tfTenDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 300, 40));

        tfLinkNV.setEnabled(false);
        tfLinkNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfLinkNVActionPerformed(evt);
            }
        });
        jPanel1.add(tfLinkNV, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 190, 180, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Username:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1093, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 665, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinimize4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimize4MouseClicked
        this.setState(this.ICONIFIED);
    }//GEN-LAST:event_btnMinimize4MouseClicked

    private void lbThoat5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThoat5MouseClicked
        int click=JOptionPane.showConfirmDialog(null, "Do you want to exit this program?", "Message", 2);
        if(click==JOptionPane.YES_OPTION)
        {
            this.setVisible(false);
        }
    }//GEN-LAST:event_lbThoat5MouseClicked

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        tfMaNV.setEnabled(false);
        int xacNhan = JOptionPane.showConfirmDialog(CaiDatLaiMK.this, "Are you sure to update?","Message",JOptionPane.YES_NO_OPTION);
        if(xacNhan == JOptionPane.YES_OPTION){
            nhanVien = new NhanVien();
            nhanVien.setMaNV(Integer.parseInt(tfMaNV.getText()));
            nhanVien.setTenNV(tfTenNV.getText());
            nhanVien.setNgaySinh(new java.sql.Date(tfNgaySinh.getDate().getTime()).toString());
            nhanVien.setSoDT(tfsoDT.getText());   
            nhanVien.setDiaChi(tfDiaChi.getText());           
            nhanVien.setTenDangNhap(tfTenDangNhap.getText());
            nhanVien.setMatKhau(String.valueOf(tfMatKhau.getPassword()));
            nhanVien.setImageNV(tfLinkNV.getText());
           
            nhanVienSERVICE.suaNhanVien2(nhanVien);
            JOptionPane.showMessageDialog(null, "Update information successfully !^^");
        }   else {
            JOptionPane.showMessageDialog(null, "Can not update!^^");
        }   
        this.setVisible(false);
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        int click=JOptionPane.showConfirmDialog(null, "Do you want to exit this program?", "Message", 2);
        if(click==JOptionPane.YES_OPTION)
        {
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void tfDiaChiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDiaChiActionPerformed

    }//GEN-LAST:event_tfDiaChiActionPerformed

    private void btnAnNLMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAnNLMKMouseClicked
        btnAnNLMK.setVisible(false);
        btnHienNLMK.setVisible(true);
        tfMatKhau.setEchoChar((char)0);      
    }//GEN-LAST:event_btnAnNLMKMouseClicked

    private void btnHienNLMKMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHienNLMKMouseClicked
        btnAnNLMK.setVisible(true);
        btnHienNLMK.setVisible(false);
        tfMatKhau.setEchoChar('*');
    }//GEN-LAST:event_btnHienNLMKMouseClicked

    private void tfTenNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenNVActionPerformed

    private void tfsoDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfsoDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfsoDTActionPerformed

    private void lbImageNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbImageNVMouseClicked
        ChonAnhNV();
    }//GEN-LAST:event_lbImageNVMouseClicked

    private void btnUploadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUploadMouseClicked
        JFileChooser open=new JFileChooser();
        int file=open.showOpenDialog(null);
        if(file==JFileChooser.APPROVE_OPTION){
            tfMaNV.setText(open.getCurrentDirectory().toString()+"\\"+open.getSelectedFile().getName());
                ImageIcon icon = new ImageIcon(tfLinkNV.getText());
                lbImageNV.setIcon(icon);
            }
    }//GEN-LAST:event_btnUploadMouseClicked

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        ChonAnhNV();
    }//GEN-LAST:event_btnUploadActionPerformed

    private void tfTenDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTenDangNhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTenDangNhapActionPerformed

    private void tfMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMatKhauActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMatKhauActionPerformed

    private void tfLinkNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfLinkNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfLinkNVActionPerformed

    private void tfMaNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMaNVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMaNVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CaiDatLaiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CaiDatLaiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CaiDatLaiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CaiDatLaiMK.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CaiDatLaiMK().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnAnNLMK;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JLabel btnHienNLMK;
    private javax.swing.JLabel btnMinimize4;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnUpload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel lbImageNV;
    private javax.swing.JLabel lbThoat5;
    public static javax.swing.JTextField tfDiaChi;
    public static javax.swing.JTextField tfLinkNV;
    private javax.swing.JTextField tfMKCu;
    public static javax.swing.JTextField tfMaNV;
    public static javax.swing.JPasswordField tfMatKhau;
    public static com.toedter.calendar.JDateChooser tfNgaySinh;
    public static javax.swing.JTextField tfTenDangNhap;
    public static javax.swing.JTextField tfTenNV;
    public static javax.swing.JTextField tfsoDT;
    // End of variables declaration//GEN-END:variables


 public void ChonAnhNV(){
        JFileChooser image = new JFileChooser();
        image.setDialogTitle("Choose 1 file!");
        image.setFileSelectionMode(JFileChooser.FILES_ONLY);
        image.setFileFilter(new FileNameExtensionFilter("Image with(jpg, png, gif)", "jpg","png","gif"));
        image.setAcceptAllFileFilterUsed(false);
        int res = image.showOpenDialog(CaiDatLaiMK.this);
        if(res==JFileChooser.APPROVE_OPTION){
            File file = image.getSelectedFile();
            String oldName = file.getName();
            String fileExtension = oldName.substring(oldName.lastIndexOf("."), oldName.length());
            String path = file.getAbsolutePath();
            String newName = new Date().getTime()+ fileExtension;
            ImageIcon imageIcon = new ImageIcon(path);
            Rectangle rerc =lbImageNV.getBounds();
            Image scaImage = imageIcon.getImage().getScaledInstance(rerc.width, rerc.height, Image.SCALE_SMOOTH);
            imageIcon = new ImageIcon(scaImage);
            lbImageNV.setIcon(imageIcon);
            tfMaNV.setText(file.getName());
        }else{
            JOptionPane.showMessageDialog(this, "No Photo!!");
        }
    }


}

